// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cluster

import (
	"context"

	"github.com/onsi/ginkgo/v2"

	metav1alpha1 "github.com/pingcap/tidb-operator/api/v2/meta/v1alpha1"
	coreutil "github.com/pingcap/tidb-operator/v2/pkg/apiutil/core/v1alpha1"
	"github.com/pingcap/tidb-operator/v2/pkg/runtime/scope"
	"github.com/pingcap/tidb-operator/v2/tests/e2e/data"
	"github.com/pingcap/tidb-operator/v2/tests/e2e/framework"
	wopt "github.com/pingcap/tidb-operator/v2/tests/e2e/framework/workload"
	"github.com/pingcap/tidb-operator/v2/tests/e2e/label"
	"github.com/pingcap/tidb-operator/v2/tests/e2e/utils/cert"
)

var _ = ginkgo.Describe("TLS", label.Cluster, label.FeatureTLS, func() {
	f := framework.New()
	f.Setup()

	f.DescribeFeatureTable(func(fs ...metav1alpha1.Feature) {
		f.SetupCluster(data.WithClusterTLSEnabled(), data.WithFeatureGates(fs...))
		workload := f.SetupWorkload()
		cm := f.SetupCertManager()

		ginkgo.It("should enable internal TLS with same ca secret", func(ctx context.Context) {
			f.MustCreateS3(ctx)
			ns := f.Namespace.Name
			cluster := f.Cluster.Name

			pdg := f.MustCreatePD(ctx,
				data.WithMSMode(),
			)
			tg := f.MustCreateTSO(ctx)
			sg := f.MustCreateScheduling(ctx)
			kvg := f.MustCreateTiKV(ctx)
			dbg := f.MustCreateTiDB(ctx,
				// TLS secret name is generated by group name.
				// Avoid name conflict because we use bundle to inject ca and
				// bundle is cluster scoped resource.
				data.WithName[scope.TiDBGroup](ns+"-dbg"),
				data.WithTiDBMySQLTLS("", ""),
			)
			fgc := f.MustCreateTiFlash(ctx,
				data.WithTiFlashComputeMode(),
			)
			fgw := f.MustCreateTiFlash(ctx,
				data.WithTiFlashWriteMode(),
			)
			cg := f.MustCreateTiCDC(ctx)
			pg := f.MustCreateTiProxy(ctx)

			cm.Install(ctx, ns, cluster)

			f.WaitForPDGroupReady(ctx, pdg)
			f.WaitForTSOGroupReady(ctx, tg)
			f.WaitForSchedulingGroupReady(ctx, sg)
			f.WaitForTiKVGroupReady(ctx, kvg)
			f.WaitForTiDBGroupReady(ctx, dbg)
			f.WaitForTiFlashGroupReady(ctx, fgc)
			f.WaitForTiFlashGroupReady(ctx, fgw)
			f.WaitForTiCDCGroupReady(ctx, cg)
			f.WaitForTiProxyGroupReady(ctx, pg)

			workload.MustPing(ctx,
				ns+"-dbg-tidb",
				wopt.TLS(cert.MySQLClient(
					coreutil.TiDBGroupMySQLCASecretName(dbg),
					coreutil.TiDBGroupMySQLCertKeyPairSecretName(dbg),
				)),
			)
			workload.MustPing(ctx, data.DefaultTiProxyServiceName, wopt.Port(data.DefaultTiProxyServicePort))
		})
	},
		[]metav1alpha1.Feature{},
	)
})
