// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CompactBackupLister helps list CompactBackups.
// All objects returned here must be treated as read-only.
type CompactBackupLister interface {
	// List lists all CompactBackups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CompactBackup, err error)
	// CompactBackups returns an object that can list and get CompactBackups.
	CompactBackups(namespace string) CompactBackupNamespaceLister
	CompactBackupListerExpansion
}

// compactBackupLister implements the CompactBackupLister interface.
type compactBackupLister struct {
	indexer cache.Indexer
}

// NewCompactBackupLister returns a new CompactBackupLister.
func NewCompactBackupLister(indexer cache.Indexer) CompactBackupLister {
	return &compactBackupLister{indexer: indexer}
}

// List lists all CompactBackups in the indexer.
func (s *compactBackupLister) List(selector labels.Selector) (ret []*v1alpha1.CompactBackup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CompactBackup))
	})
	return ret, err
}

// CompactBackups returns an object that can list and get CompactBackups.
func (s *compactBackupLister) CompactBackups(namespace string) CompactBackupNamespaceLister {
	return compactBackupNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CompactBackupNamespaceLister helps list and get CompactBackups.
// All objects returned here must be treated as read-only.
type CompactBackupNamespaceLister interface {
	// List lists all CompactBackups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CompactBackup, err error)
	// Get retrieves the CompactBackup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.CompactBackup, error)
	CompactBackupNamespaceListerExpansion
}

// compactBackupNamespaceLister implements the CompactBackupNamespaceLister
// interface.
type compactBackupNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CompactBackups in the indexer for a given namespace.
func (s compactBackupNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.CompactBackup, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CompactBackup))
	})
	return ret, err
}

// Get retrieves the CompactBackup from the indexer for a given namespace and name.
func (s compactBackupNamespaceLister) Get(name string) (*v1alpha1.CompactBackup, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("compactbackup"), name)
	}
	return obj.(*v1alpha1.CompactBackup), nil
}
