// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BackupListerExpansion allows custom methods to be added to
// BackupLister.
type BackupListerExpansion interface{}

// BackupNamespaceListerExpansion allows custom methods to be added to
// BackupNamespaceLister.
type BackupNamespaceListerExpansion interface{}

// BackupScheduleListerExpansion allows custom methods to be added to
// BackupScheduleLister.
type BackupScheduleListerExpansion interface{}

// BackupScheduleNamespaceListerExpansion allows custom methods to be added to
// BackupScheduleNamespaceLister.
type BackupScheduleNamespaceListerExpansion interface{}

// DMClusterListerExpansion allows custom methods to be added to
// DMClusterLister.
type DMClusterListerExpansion interface{}

// DMClusterNamespaceListerExpansion allows custom methods to be added to
// DMClusterNamespaceLister.
type DMClusterNamespaceListerExpansion interface{}

// DataResourceListerExpansion allows custom methods to be added to
// DataResourceLister.
type DataResourceListerExpansion interface{}

// DataResourceNamespaceListerExpansion allows custom methods to be added to
// DataResourceNamespaceLister.
type DataResourceNamespaceListerExpansion interface{}

// RestoreListerExpansion allows custom methods to be added to
// RestoreLister.
type RestoreListerExpansion interface{}

// RestoreNamespaceListerExpansion allows custom methods to be added to
// RestoreNamespaceLister.
type RestoreNamespaceListerExpansion interface{}

// TidbClusterListerExpansion allows custom methods to be added to
// TidbClusterLister.
type TidbClusterListerExpansion interface{}

// TidbClusterNamespaceListerExpansion allows custom methods to be added to
// TidbClusterNamespaceLister.
type TidbClusterNamespaceListerExpansion interface{}

// TidbClusterAutoScalerListerExpansion allows custom methods to be added to
// TidbClusterAutoScalerLister.
type TidbClusterAutoScalerListerExpansion interface{}

// TidbClusterAutoScalerNamespaceListerExpansion allows custom methods to be added to
// TidbClusterAutoScalerNamespaceLister.
type TidbClusterAutoScalerNamespaceListerExpansion interface{}

// TidbInitializerListerExpansion allows custom methods to be added to
// TidbInitializerLister.
type TidbInitializerListerExpansion interface{}

// TidbInitializerNamespaceListerExpansion allows custom methods to be added to
// TidbInitializerNamespaceLister.
type TidbInitializerNamespaceListerExpansion interface{}

// TidbMonitorListerExpansion allows custom methods to be added to
// TidbMonitorLister.
type TidbMonitorListerExpansion interface{}

// TidbMonitorNamespaceListerExpansion allows custom methods to be added to
// TidbMonitorNamespaceLister.
type TidbMonitorNamespaceListerExpansion interface{}
