// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TidbNGMonitoringLister helps list TidbNGMonitorings.
// All objects returned here must be treated as read-only.
type TidbNGMonitoringLister interface {
	// List lists all TidbNGMonitorings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TidbNGMonitoring, err error)
	// TidbNGMonitorings returns an object that can list and get TidbNGMonitorings.
	TidbNGMonitorings(namespace string) TidbNGMonitoringNamespaceLister
	TidbNGMonitoringListerExpansion
}

// tidbNGMonitoringLister implements the TidbNGMonitoringLister interface.
type tidbNGMonitoringLister struct {
	indexer cache.Indexer
}

// NewTidbNGMonitoringLister returns a new TidbNGMonitoringLister.
func NewTidbNGMonitoringLister(indexer cache.Indexer) TidbNGMonitoringLister {
	return &tidbNGMonitoringLister{indexer: indexer}
}

// List lists all TidbNGMonitorings in the indexer.
func (s *tidbNGMonitoringLister) List(selector labels.Selector) (ret []*v1alpha1.TidbNGMonitoring, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TidbNGMonitoring))
	})
	return ret, err
}

// TidbNGMonitorings returns an object that can list and get TidbNGMonitorings.
func (s *tidbNGMonitoringLister) TidbNGMonitorings(namespace string) TidbNGMonitoringNamespaceLister {
	return tidbNGMonitoringNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TidbNGMonitoringNamespaceLister helps list and get TidbNGMonitorings.
// All objects returned here must be treated as read-only.
type TidbNGMonitoringNamespaceLister interface {
	// List lists all TidbNGMonitorings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TidbNGMonitoring, err error)
	// Get retrieves the TidbNGMonitoring from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.TidbNGMonitoring, error)
	TidbNGMonitoringNamespaceListerExpansion
}

// tidbNGMonitoringNamespaceLister implements the TidbNGMonitoringNamespaceLister
// interface.
type tidbNGMonitoringNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all TidbNGMonitorings in the indexer for a given namespace.
func (s tidbNGMonitoringNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.TidbNGMonitoring, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TidbNGMonitoring))
	})
	return ret, err
}

// Get retrieves the TidbNGMonitoring from the indexer for a given namespace and name.
func (s tidbNGMonitoringNamespaceLister) Get(name string) (*v1alpha1.TidbNGMonitoring, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("tidbngmonitoring"), name)
	}
	return obj.(*v1alpha1.TidbNGMonitoring), nil
}
