FROM pingcap/pingcap-base:v1

RUN dnf install -y tzdata bash bind-utils && dnf clean all

ADD bin/tidb-scheduler /usr/local/bin/tidb-scheduler
ADD bin/tidb-discovery /usr/local/bin/tidb-discovery
ADD bin/tidb-controller-manager /usr/local/bin/tidb-controller-manager
ADD bin/tidb-admission-webhook /usr/local/bin/tidb-admission-webhook

ADD e2e-entrypoint.sh /e2e-entrypoint.sh
