FROM ghcr.io/pingcap-qe/bases/pingcap-base:v1.12.2@sha256:07772021ca1a9e31f6f89c745c15a577a1cd752da3c6df0f64e9453b8091cfb9

RUN dnf install -y tzdata bash bind-utils && dnf clean all

ADD bin/tidb-scheduler /usr/local/bin/tidb-scheduler
ADD bin/tidb-discovery /usr/local/bin/tidb-discovery
ADD bin/tidb-controller-manager /usr/local/bin/tidb-controller-manager
ADD bin/tidb-admission-webhook /usr/local/bin/tidb-admission-webhook

ADD e2e-entrypoint.sh /e2e-entrypoint.sh
