// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"flag"
	"github.com/pingcap/tidb-operator/pkg/initializer"
	"github.com/pingcap/tidb-operator/pkg/version"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/component-base/logs"
	"k8s.io/klog"
	"os"
)

var (
	printVersion     bool
	namespace        string
	component        string
	verifyPeriodDays int
)

func init() {
	flag.BoolVar(&printVersion, "V", false, "Show version and quit")
	flag.BoolVar(&printVersion, "version", false, "Show version and quit")
	flag.StringVar(&component, "component", "all", "The component to initializer resource for")
	flag.IntVar(&verifyPeriodDays, "verifyPeriodDays", 365, "Number of days a certificate generated by -x509 is valid for.")
	flag.BoolVar(&initializer.WebhookEnabled, "webhookEnabled", false, "switch to enable init webhook resource")
	flag.Parse()

	namespace = os.Getenv("NAMESPACE")
	if len(namespace) == 0 {
		klog.Fatalf("ENV NAMESPACE not set")
	}

}

func main() {

	if printVersion {
		version.PrintVersionInfo()
		os.Exit(0)
	}
	version.LogVersionInfo()

	logs.InitLogs()
	defer logs.FlushLogs()

	cfg, err := rest.InClusterConfig()
	if err != nil {
		klog.Fatalf("failed to get config: %v", err)
	}

	kubeCli, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		klog.Fatalf("failed to get kubeCli: %v", err)
	}

	init := initializer.NewInitializer(kubeCli)

	err = init.Run(namespace, component, verifyPeriodDays)
	if err != nil {
		klog.Fatalf("failed to init resources for %s: %v", component, err)
	}
}
