//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package scope

import (
	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	"github.com/pingcap/tidb-operator/pkg/runtime"
)

type (
	TiKV struct{}
)

func (TiKV) From(f *v1alpha1.TiKV) *runtime.TiKV {
	return runtime.FromTiKV(f)
}

func (TiKV) To(t *runtime.TiKV) *v1alpha1.TiKV {
	return runtime.ToTiKV(t)
}

func (TiKV) Component() string {
	return v1alpha1.LabelValComponentTiKV
}

func (TiKV) NewList() *v1alpha1.TiKVList {
	return &v1alpha1.TiKVList{}
}

func (TiKV) GetItems(l *v1alpha1.TiKVList) []*v1alpha1.TiKV {
	items := make([]*v1alpha1.TiKV, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

type TiKVGroup struct{}

func (TiKVGroup) From(f *v1alpha1.TiKVGroup) *runtime.TiKVGroup {
	return runtime.FromTiKVGroup(f)
}

func (TiKVGroup) To(t *runtime.TiKVGroup) *v1alpha1.TiKVGroup {
	return runtime.ToTiKVGroup(t)
}

func (TiKVGroup) Component() string {
	return v1alpha1.LabelValComponentTiKV
}

func (TiKVGroup) NewList() *v1alpha1.TiKVGroupList {
	return &v1alpha1.TiKVGroupList{}
}

func (TiKVGroup) GetItems(l *v1alpha1.TiKVGroupList) []*v1alpha1.TiKVGroup {
	items := make([]*v1alpha1.TiKVGroup, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

func (TiKVGroup) Instance() TiKV {
	return TiKV{}
}
