//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package scope

import (
	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	"github.com/pingcap/tidb-operator/v2/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type (
	TiKVWorker struct{}
)

func (TiKVWorker) From(f *v1alpha1.TiKVWorker) *runtime.TiKVWorker {
	return runtime.FromTiKVWorker(f)
}

func (TiKVWorker) To(t *runtime.TiKVWorker) *v1alpha1.TiKVWorker {
	return runtime.ToTiKVWorker(t)
}

func (TiKVWorker) Component() string {
	return v1alpha1.LabelValComponentTiKVWorker
}

func (TiKVWorker) GVK() schema.GroupVersionKind {
	return v1alpha1.SchemeGroupVersion.WithKind("TiKVWorker")
}

func (TiKVWorker) NewList() *v1alpha1.TiKVWorkerList {
	return &v1alpha1.TiKVWorkerList{}
}

func (TiKVWorker) GetItems(l *v1alpha1.TiKVWorkerList) []*v1alpha1.TiKVWorker {
	items := make([]*v1alpha1.TiKVWorker, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

type TiKVWorkerGroup struct{}

func (TiKVWorkerGroup) From(f *v1alpha1.TiKVWorkerGroup) *runtime.TiKVWorkerGroup {
	return runtime.FromTiKVWorkerGroup(f)
}

func (TiKVWorkerGroup) To(t *runtime.TiKVWorkerGroup) *v1alpha1.TiKVWorkerGroup {
	return runtime.ToTiKVWorkerGroup(t)
}

func (TiKVWorkerGroup) Component() string {
	return v1alpha1.LabelValComponentTiKVWorker
}

func (TiKVWorkerGroup) GVK() schema.GroupVersionKind {
	return v1alpha1.SchemeGroupVersion.WithKind("TiKVWorkerGroup")
}

func (TiKVWorkerGroup) NewList() *v1alpha1.TiKVWorkerGroupList {
	return &v1alpha1.TiKVWorkerGroupList{}
}

func (TiKVWorkerGroup) GetItems(l *v1alpha1.TiKVWorkerGroupList) []*v1alpha1.TiKVWorkerGroup {
	items := make([]*v1alpha1.TiKVWorkerGroup, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

func (TiKVWorkerGroup) Instance() TiKVWorker {
	return TiKVWorker{}
}
