//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package scope

import (
	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	"github.com/pingcap/tidb-operator/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type (
	Scheduler struct{}
)

func (Scheduler) From(f *v1alpha1.Scheduler) *runtime.Scheduler {
	return runtime.FromScheduler(f)
}

func (Scheduler) To(t *runtime.Scheduler) *v1alpha1.Scheduler {
	return runtime.ToScheduler(t)
}

func (Scheduler) Component() string {
	return v1alpha1.LabelValComponentScheduler
}

func (Scheduler) GVK() schema.GroupVersionKind {
	return v1alpha1.SchemeGroupVersion.WithKind("Scheduler")
}

func (Scheduler) NewList() *v1alpha1.SchedulerList {
	return &v1alpha1.SchedulerList{}
}

func (Scheduler) GetItems(l *v1alpha1.SchedulerList) []*v1alpha1.Scheduler {
	items := make([]*v1alpha1.Scheduler, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

type SchedulerGroup struct{}

func (SchedulerGroup) From(f *v1alpha1.SchedulerGroup) *runtime.SchedulerGroup {
	return runtime.FromSchedulerGroup(f)
}

func (SchedulerGroup) To(t *runtime.SchedulerGroup) *v1alpha1.SchedulerGroup {
	return runtime.ToSchedulerGroup(t)
}

func (SchedulerGroup) Component() string {
	return v1alpha1.LabelValComponentScheduler
}

func (SchedulerGroup) GVK() schema.GroupVersionKind {
	return v1alpha1.SchemeGroupVersion.WithKind("SchedulerGroup")
}

func (SchedulerGroup) NewList() *v1alpha1.SchedulerGroupList {
	return &v1alpha1.SchedulerGroupList{}
}

func (SchedulerGroup) GetItems(l *v1alpha1.SchedulerGroupList) []*v1alpha1.SchedulerGroup {
	items := make([]*v1alpha1.SchedulerGroup, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

func (SchedulerGroup) Instance() Scheduler {
	return Scheduler{}
}
