//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package scope

import (
	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	"github.com/pingcap/tidb-operator/v2/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type (
	DM struct{}
)

func (DM) From(f *v1alpha1.DM) *runtime.DM {
	return runtime.FromDM(f)
}

func (DM) To(t *runtime.DM) *v1alpha1.DM {
	return runtime.ToDM(t)
}

func (DM) Component() string {
	return v1alpha1.LabelValComponentDMMaster
}

func (DM) GVK() schema.GroupVersionKind {
	return v1alpha1.SchemeGroupVersion.WithKind("DM")
}

func (DM) NewList() *v1alpha1.DMList {
	return &v1alpha1.DMList{}
}

func (DM) GetItems(l *v1alpha1.DMList) []*v1alpha1.DM {
	items := make([]*v1alpha1.DM, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

type DMGroup struct{}

func (DMGroup) From(f *v1alpha1.DMGroup) *runtime.DMGroup {
	return runtime.FromDMGroup(f)
}

func (DMGroup) To(t *runtime.DMGroup) *v1alpha1.DMGroup {
	return runtime.ToDMGroup(t)
}

func (DMGroup) Component() string {
	return v1alpha1.LabelValComponentDMMaster
}

func (DMGroup) GVK() schema.GroupVersionKind {
	return v1alpha1.SchemeGroupVersion.WithKind("DMGroup")
}

func (DMGroup) NewList() *v1alpha1.DMGroupList {
	return &v1alpha1.DMGroupList{}
}

func (DMGroup) GetItems(l *v1alpha1.DMGroupList) []*v1alpha1.DMGroup {
	items := make([]*v1alpha1.DMGroup, 0, len(l.Items))
	for i := range l.Items {
		items = append(items, &l.Items[i])
	}
	return items
}

func (DMGroup) Instance() DM {
	return DM{}
}
