{
 "title": "basic-Test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "drainer_instance",
    "query": "label_values(binlog_drainer_ddl_jobs_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "pump",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "binlog_pump_storage_storage_size_bytes",
       "legendFormat": "{{instance}} : {{type}}"
      }
     ]
    },
    {
     "title": "Metadata",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      { "expr": "binlog_pump_storage_gc_ts", "legendFormat": "{{instance}} : gc_tso" },
      {
       "expr": "binlog_pump_storage_max_commit_ts",
       "legendFormat": "{{instance}} : max_commit_tso"
      }
     ]
    },
    {
     "title": "Write Binlog QPS by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(binlog_pump_rpc_duration_seconds_count{method=\"WriteBinlog\"}[1m])",
       "legendFormat": "{{instance}} :: {{label}}"
      }
     ]
    },
    {
     "title": "Write Binlog Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_pump_rpc_duration_seconds_bucket{method=\"WriteBinlog\"}[1m]))",
       "legendFormat": "{{instance}} : {{method}}:99"
      },
      {
       "expr": "histogram_quantile(0.95, rate(binlog_pump_rpc_duration_seconds_bucket{method=\"WriteBinlog\"}[1m]))",
       "legendFormat": "{{instance}} : {{method}} : 95"
      }
     ]
    },
    {
     "title": "Storage Write Binlog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_pump_storage_write_binlog_size_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}} : 99"
      },
      {
       "expr": "histogram_quantile(0.95, rate(binlog_pump_storage_write_binlog_size_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}} : 95"
      }
     ]
    },
    {
     "title": "Storage Write Binlog Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_pump_storage_write_binlog_duration_time_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}}:99"
      },
      {
       "expr": "histogram_quantile(0.95, rate(binlog_pump_storage_write_binlog_duration_time_bucket[1m]))",
       "legendFormat": "{{instance}} : {{type}}:95"
      }
     ]
    },
    {
     "title": "Pump Storage Error By Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(binlog_pump_storage_error_count[1m])",
       "legendFormat": "{{instance}}:{{type}}"
      }
     ]
    },
    {
     "title": "Query Tikv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "binlog_pump_storage_query_tikv_count",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TiDB Server Skip Binlog Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_server_critical_error_total",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "drainer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoint TSO",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "binlog_drainer_checkpoint_tso{instance = \"$drainer_instance\"}",
       "legendFormat": "checkpoint tso"
      }
     ]
    },
    {
     "title": "Pump Handle TSO",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_pump_position{instance = \"$drainer_instance\"}",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Pull Binlog QPS by  Pump NodeID",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(binlog_drainer_read_binlog_size_count{instance = \"$drainer_instance\"}[1m])) by (nodeID)",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "95% Binlog Reach Duration By Pump",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(binlog_drainer_binlog_reach_duration_time_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "{{nodeID}}"
      }
     ]
    },
    {
     "title": "Error By Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_error_count{instance = \"$drainer_instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Drainer Event",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(binlog_drainer_event{instance = \"$drainer_instance\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% Execute Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_drainer_execute_duration_time_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "{{component}}"
      }
     ]
    },
    {
     "title": "99% sql query Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(binlog_drainer_query_duration_time_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "95% Binlog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(binlog_drainer_read_binlog_size_bucket{instance = \"$drainer_instance\"}[1m]))",
       "legendFormat": "pump: {{nodeID}}"
      }
     ]
    },
    {
     "title": "DDL Job Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_ddl_jobs_total{instance = \"$drainer_instance\"}",
       "legendFormat": "ddl job count"
      }
     ]
    },
    {
     "title": "queue size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "binlog_drainer_queue_size{instance = \"$drainer_instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutine",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{component=~\"binlog|pump|drainer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{component=~\"binlog|pump|drainer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}