//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package runtime

import (
	"time"
	"unsafe"

	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	metav1alpha1 "github.com/pingcap/tidb-operator/api/v2/meta/v1alpha1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/utils/ptr"
)

type (
	Router v1alpha1.Router
)

type RouterTuple struct{}

var _ InstanceTuple[*v1alpha1.Router, *Router] = RouterTuple{}

func (RouterTuple) From(t *v1alpha1.Router) *Router {
	return FromRouter(t)
}

func (RouterTuple) FromSlice(t []*v1alpha1.Router) []*Router {
	return FromRouterSlice(t)
}

func (RouterTuple) To(t *Router) *v1alpha1.Router {
	return ToRouter(t)
}

func (RouterTuple) ToSlice(t []*Router) []*v1alpha1.Router {
	return ToRouterSlice(t)
}

func FromRouter(in *v1alpha1.Router) *Router {
	return (*Router)(in)
}

func ToRouter(in *Router) *v1alpha1.Router {
	return (*v1alpha1.Router)(in)
}

func FromRouterSlice(ins []*v1alpha1.Router) []*Router {
	return *(*[]*Router)(unsafe.Pointer(&ins))
}

func ToRouterSlice(ins []*Router) []*v1alpha1.Router {
	return *(*[]*v1alpha1.Router)(unsafe.Pointer(&ins))
}

var _ Instance = &Router{}

func (in *Router) DeepCopyObject() runtime.Object {
	return (*v1alpha1.Router)(in).DeepCopyObject()
}

func (in *Router) To() *v1alpha1.Router {
	return ToRouter(in)
}

func (in *Router) GetTopology() v1alpha1.Topology {
	return in.Spec.Topology
}

func (in *Router) SetTopology(t v1alpha1.Topology) {
	in.Spec.Topology = t
}

func (in *Router) GetUpdateRevision() string {
	if in.Labels == nil {
		return ""
	}
	return in.Labels[v1alpha1.LabelKeyInstanceRevisionHash]
}

func (in *Router) CurrentRevision() string {
	return in.Status.CurrentRevision
}

func (in *Router) SetCurrentRevision(rev string) {
	in.Status.CurrentRevision = rev
}

func (in *Router) IsReady() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}

	return cond.Status == metav1.ConditionTrue
}

func (in *Router) IsNotRunning() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondRunning)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	return cond.Status == metav1.ConditionFalse
}

func (in *Router) IsAvailable(minReadySeconds int64, now time.Time) bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	if cond.Status != metav1.ConditionTrue {
		return false
	}
	if minReadySeconds == 0 {
		return true
	}
	minReadySecondsDuration := time.Duration(minReadySeconds) * time.Second
	if !cond.LastTransitionTime.IsZero() && cond.LastTransitionTime.Add(minReadySecondsDuration).Before(now) {
		return true
	}

	return false
}

func (in *Router) IsUpToDate() bool {
	return in.Status.ObservedGeneration == in.GetGeneration() && in.GetUpdateRevision() == in.Status.CurrentRevision
}

func (in *Router) Conditions() []metav1.Condition {
	return in.Status.Conditions
}

func (in *Router) SetConditions(conds []metav1.Condition) {
	in.Status.Conditions = conds
}

func (in *Router) ObservedGeneration() int64 {
	return in.Status.ObservedGeneration
}

func (in *Router) SetObservedGeneration(gen int64) {
	in.Status.ObservedGeneration = gen
}

func (in *Router) SetCluster(cluster string) {
	in.Spec.Cluster.Name = cluster
}

func (in *Router) Cluster() string {
	return in.Spec.Cluster.Name
}

func (*Router) Component() string {
	return v1alpha1.LabelValComponentRouter
}

func (in *Router) Volumes() []v1alpha1.Volume {
	return in.Spec.Volumes
}

func (in *Router) PodOverlay() *v1alpha1.PodOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.Pod
}

func (in *Router) PVCOverlay() []v1alpha1.NamedPersistentVolumeClaimOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.PersistentVolumeClaims
}

func (in *Router) Features() []metav1alpha1.Feature {
	return in.Spec.Features
}

func (in *Router) SetVersion(version string) {
	in.Spec.Version = version
}

func (in *Router) Version() string {
	return in.Spec.Version
}

func (in *Router) SetImage(image string) {
	in.Spec.Image = ptr.To(image)
}

func (in *Router) Subdomain() string {
	return in.Spec.Subdomain
}

func (in *Router) ServerLabels() map[string]string {
	return nil
}

func (in *Router) ClusterCertKeyPairSecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *Router) ClusterCASecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *Router) IsOffline() bool {
	return false
}

func (in *Router) IsStore() bool {
	return false
}

type (
	RouterGroup v1alpha1.RouterGroup
)

type RouterGroupTuple struct{}

var _ GroupTuple[*v1alpha1.RouterGroup, *RouterGroup] = RouterGroupTuple{}

func (RouterGroupTuple) From(t *v1alpha1.RouterGroup) *RouterGroup {
	return FromRouterGroup(t)
}

func (RouterGroupTuple) FromSlice(t []*v1alpha1.RouterGroup) []*RouterGroup {
	return FromRouterGroupSlice(t)
}

func (RouterGroupTuple) To(t *RouterGroup) *v1alpha1.RouterGroup {
	return ToRouterGroup(t)
}

func (RouterGroupTuple) ToSlice(t []*RouterGroup) []*v1alpha1.RouterGroup {
	return ToRouterGroupSlice(t)
}

func FromRouterGroup(g *v1alpha1.RouterGroup) *RouterGroup {
	return (*RouterGroup)(g)
}

func ToRouterGroup(g *RouterGroup) *v1alpha1.RouterGroup {
	return (*v1alpha1.RouterGroup)(g)
}

func FromRouterGroupSlice(gs []*v1alpha1.RouterGroup) []*RouterGroup {
	return *(*[]*RouterGroup)(unsafe.Pointer(&gs))
}

func ToRouterGroupSlice(gs []*RouterGroup) []*v1alpha1.RouterGroup {
	return *(*[]*v1alpha1.RouterGroup)(unsafe.Pointer(&gs))
}

var _ Group = &RouterGroup{}

func (g *RouterGroup) DeepCopyObject() runtime.Object {
	return (*v1alpha1.RouterGroup)(g)
}

func (g *RouterGroup) To() *v1alpha1.RouterGroup {
	return ToRouterGroup(g)
}

func (g *RouterGroup) SetReplicas(replicas int32) {
	g.Spec.Replicas = &replicas
}

func (g *RouterGroup) Replicas() int32 {
	if g.Spec.Replicas == nil {
		return 1
	}
	return *g.Spec.Replicas
}

func (g *RouterGroup) SetVersion(version string) {
	g.Spec.Template.Spec.Version = version
}

func (g *RouterGroup) Version() string {
	return g.Spec.Template.Spec.Version
}

func (g *RouterGroup) SetImage(image string) {
	g.Spec.Template.Spec.Image = ptr.To(image)
}

func (g *RouterGroup) SetCluster(cluster string) {
	g.Spec.Cluster.Name = cluster
}

func (g *RouterGroup) Cluster() string {
	return g.Spec.Cluster.Name
}

func (*RouterGroup) Component() string {
	return v1alpha1.LabelValComponentRouter
}

func (g *RouterGroup) Conditions() []metav1.Condition {
	return g.Status.Conditions
}

func (g *RouterGroup) SetConditions(conds []metav1.Condition) {
	g.Status.Conditions = conds
}

func (g *RouterGroup) ObservedGeneration() int64 {
	return g.Status.ObservedGeneration
}

func (g *RouterGroup) SetObservedGeneration(gen int64) {
	g.Status.ObservedGeneration = gen
}

func (g *RouterGroup) SetStatusVersion(version string) {
	g.Status.Version = version
}

func (g *RouterGroup) StatusVersion() string {
	return g.Status.Version
}

func (g *RouterGroup) SetStatusReplicas(replicas, ready, update, current int32) {
	g.Status.Replicas = replicas
	g.Status.ReadyReplicas = ready
	g.Status.UpdatedReplicas = update
	g.Status.CurrentReplicas = current
}

func (g *RouterGroup) StatusReplicas() (replicas, ready, update, current int32) {
	return g.Status.Replicas,
		g.Status.ReadyReplicas,
		g.Status.UpdatedReplicas,
		g.Status.CurrentReplicas
}

func (g *RouterGroup) SetStatusRevision(update, current string, collisionCount *int32) {
	g.Status.UpdateRevision = update
	g.Status.CurrentRevision = current
	g.Status.CollisionCount = collisionCount
}

func (g *RouterGroup) StatusRevision() (update, current string, collisionCount *int32) {
	return g.Status.UpdateRevision,
		g.Status.CurrentRevision,
		g.Status.CollisionCount
}

func (g *RouterGroup) SetStatusSelector(l string) {
	g.Status.Selector = l
}

func (g *RouterGroup) StatusSelector() string {
	return g.Status.Selector
}

func (g *RouterGroup) TemplateLabels() map[string]string {
	return g.Spec.Template.Labels
}

func (g *RouterGroup) TemplateAnnotations() map[string]string {
	return g.Spec.Template.Annotations
}

func (g *RouterGroup) SetTemplateLabels(ls map[string]string) {
	g.Spec.Template.Labels = ls
}

func (g *RouterGroup) SetTemplateAnnotations(anno map[string]string) {
	g.Spec.Template.Annotations = anno
}

func (g *RouterGroup) Features() []metav1alpha1.Feature {
	return g.Spec.Features
}

func (g *RouterGroup) SetTemplateClusterTLS(ca, certKeyPair string) {
	if g.Spec.Template.Spec.Security == nil {
		g.Spec.Template.Spec.Security = &v1alpha1.Security{}
	}
	sec := g.Spec.Template.Spec.Security
	if sec.TLS == nil {
		sec.TLS = &v1alpha1.ComponentTLSConfig{}
	}
	sec.TLS.Cluster = &v1alpha1.InternalTLS{}
	if ca != "" {
		sec.TLS.Cluster.CA = &v1alpha1.CAReference{
			Name: ca,
		}
	}
	if certKeyPair != "" {
		sec.TLS.Cluster.CertKeyPair = &v1alpha1.CertKeyPairReference{
			Name: certKeyPair,
		}
	}
}

func (g *RouterGroup) ClusterCertKeyPairSecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	return defaultName
}

func (g *RouterGroup) ClusterCASecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	return defaultName
}

func (g *RouterGroup) MinReadySeconds() int64 {
	if g.Spec.MinReadySeconds == nil {
		return v1alpha1.DefaultRouterMinReadySeconds
	}
	return *g.Spec.MinReadySeconds
}

func (g *RouterGroup) SchedulePolicies() []v1alpha1.SchedulePolicy {
	return g.Spec.SchedulePolicies
}
