//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package runtime

import (
	"time"
	"unsafe"

	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	metav1alpha1 "github.com/pingcap/tidb-operator/api/v2/meta/v1alpha1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/utils/ptr"
)

type (
	Scheduling v1alpha1.Scheduling
)

type SchedulingTuple struct{}

var _ InstanceTuple[*v1alpha1.Scheduling, *Scheduling] = SchedulingTuple{}

func (SchedulingTuple) From(t *v1alpha1.Scheduling) *Scheduling {
	return FromScheduling(t)
}

func (SchedulingTuple) FromSlice(t []*v1alpha1.Scheduling) []*Scheduling {
	return FromSchedulingSlice(t)
}

func (SchedulingTuple) To(t *Scheduling) *v1alpha1.Scheduling {
	return ToScheduling(t)
}

func (SchedulingTuple) ToSlice(t []*Scheduling) []*v1alpha1.Scheduling {
	return ToSchedulingSlice(t)
}

func FromScheduling(in *v1alpha1.Scheduling) *Scheduling {
	return (*Scheduling)(in)
}

func ToScheduling(in *Scheduling) *v1alpha1.Scheduling {
	return (*v1alpha1.Scheduling)(in)
}

func FromSchedulingSlice(ins []*v1alpha1.Scheduling) []*Scheduling {
	return *(*[]*Scheduling)(unsafe.Pointer(&ins))
}

func ToSchedulingSlice(ins []*Scheduling) []*v1alpha1.Scheduling {
	return *(*[]*v1alpha1.Scheduling)(unsafe.Pointer(&ins))
}

var _ Instance = &Scheduling{}

func (in *Scheduling) DeepCopyObject() runtime.Object {
	return (*v1alpha1.Scheduling)(in).DeepCopyObject()
}

func (in *Scheduling) To() *v1alpha1.Scheduling {
	return ToScheduling(in)
}

func (in *Scheduling) GetTopology() v1alpha1.Topology {
	return in.Spec.Topology
}

func (in *Scheduling) SetTopology(t v1alpha1.Topology) {
	in.Spec.Topology = t
}

func (in *Scheduling) GetUpdateRevision() string {
	if in.Labels == nil {
		return ""
	}
	return in.Labels[v1alpha1.LabelKeyInstanceRevisionHash]
}

func (in *Scheduling) CurrentRevision() string {
	return in.Status.CurrentRevision
}

func (in *Scheduling) SetCurrentRevision(rev string) {
	in.Status.CurrentRevision = rev
}

func (in *Scheduling) IsReady() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}

	return cond.Status == metav1.ConditionTrue
}

func (in *Scheduling) IsNotRunning() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondRunning)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	return cond.Status == metav1.ConditionFalse
}

func (in *Scheduling) IsAvailable(minReadySeconds int64, now time.Time) bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	if cond.Status != metav1.ConditionTrue {
		return false
	}
	if minReadySeconds == 0 {
		return true
	}
	minReadySecondsDuration := time.Duration(minReadySeconds) * time.Second
	if !cond.LastTransitionTime.IsZero() && cond.LastTransitionTime.Add(minReadySecondsDuration).Before(now) {
		return true
	}

	return false
}

func (in *Scheduling) IsUpToDate() bool {
	return in.Status.ObservedGeneration == in.GetGeneration() && in.GetUpdateRevision() == in.Status.CurrentRevision
}

func (in *Scheduling) Conditions() []metav1.Condition {
	return in.Status.Conditions
}

func (in *Scheduling) SetConditions(conds []metav1.Condition) {
	in.Status.Conditions = conds
}

func (in *Scheduling) ObservedGeneration() int64 {
	return in.Status.ObservedGeneration
}

func (in *Scheduling) SetObservedGeneration(gen int64) {
	in.Status.ObservedGeneration = gen
}

func (in *Scheduling) SetCluster(cluster string) {
	in.Spec.Cluster.Name = cluster
}

func (in *Scheduling) Cluster() string {
	return in.Spec.Cluster.Name
}

func (*Scheduling) Component() string {
	return v1alpha1.LabelValComponentScheduling
}

func (in *Scheduling) Volumes() []v1alpha1.Volume {
	return in.Spec.Volumes
}

func (in *Scheduling) PodOverlay() *v1alpha1.PodOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.Pod
}

func (in *Scheduling) PVCOverlay() []v1alpha1.NamedPersistentVolumeClaimOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.PersistentVolumeClaims
}

func (in *Scheduling) Features() []metav1alpha1.Feature {
	return in.Spec.Features
}

func (in *Scheduling) SetVersion(version string) {
	in.Spec.Version = version
}

func (in *Scheduling) Version() string {
	return in.Spec.Version
}

func (in *Scheduling) SetImage(image string) {
	in.Spec.Image = ptr.To(image)
}

func (in *Scheduling) Subdomain() string {
	return in.Spec.Subdomain
}

func (in *Scheduling) ClusterCertKeyPairSecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *Scheduling) ClusterCASecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *Scheduling) ClientCertKeyPairSecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Client != nil && sec.TLS.Client.CertKeyPair != nil {
		return sec.TLS.Client.CertKeyPair.Name
	}
	return in.Cluster() + "-cluster-client-secret"
}

func (in *Scheduling) ClientCASecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Client != nil && sec.TLS.Client.CA != nil {
		return sec.TLS.Client.CA.Name
	}
	return in.Cluster() + "-cluster-client-secret"
}

func (in *Scheduling) ClientInsecureSkipTLSVerify() bool {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Client != nil && sec.TLS.Client.CA != nil {
		return sec.TLS.Client.InsecureSkipTLSVerify
	}
	return false
}

func (in *Scheduling) IsOffline() bool {
	return false
}

func (in *Scheduling) IsStore() bool {
	return false
}

type (
	SchedulingGroup v1alpha1.SchedulingGroup
)

type SchedulingGroupTuple struct{}

var _ GroupTuple[*v1alpha1.SchedulingGroup, *SchedulingGroup] = SchedulingGroupTuple{}

func (SchedulingGroupTuple) From(t *v1alpha1.SchedulingGroup) *SchedulingGroup {
	return FromSchedulingGroup(t)
}

func (SchedulingGroupTuple) FromSlice(t []*v1alpha1.SchedulingGroup) []*SchedulingGroup {
	return FromSchedulingGroupSlice(t)
}

func (SchedulingGroupTuple) To(t *SchedulingGroup) *v1alpha1.SchedulingGroup {
	return ToSchedulingGroup(t)
}

func (SchedulingGroupTuple) ToSlice(t []*SchedulingGroup) []*v1alpha1.SchedulingGroup {
	return ToSchedulingGroupSlice(t)
}

func FromSchedulingGroup(g *v1alpha1.SchedulingGroup) *SchedulingGroup {
	return (*SchedulingGroup)(g)
}

func ToSchedulingGroup(g *SchedulingGroup) *v1alpha1.SchedulingGroup {
	return (*v1alpha1.SchedulingGroup)(g)
}

func FromSchedulingGroupSlice(gs []*v1alpha1.SchedulingGroup) []*SchedulingGroup {
	return *(*[]*SchedulingGroup)(unsafe.Pointer(&gs))
}

func ToSchedulingGroupSlice(gs []*SchedulingGroup) []*v1alpha1.SchedulingGroup {
	return *(*[]*v1alpha1.SchedulingGroup)(unsafe.Pointer(&gs))
}

var _ Group = &SchedulingGroup{}

func (g *SchedulingGroup) DeepCopyObject() runtime.Object {
	return (*v1alpha1.SchedulingGroup)(g)
}

func (g *SchedulingGroup) To() *v1alpha1.SchedulingGroup {
	return ToSchedulingGroup(g)
}

func (g *SchedulingGroup) SetReplicas(replicas int32) {
	g.Spec.Replicas = &replicas
}

func (g *SchedulingGroup) Replicas() int32 {
	if g.Spec.Replicas == nil {
		return 1
	}
	return *g.Spec.Replicas
}

func (g *SchedulingGroup) SetVersion(version string) {
	g.Spec.Template.Spec.Version = version
}

func (g *SchedulingGroup) Version() string {
	return g.Spec.Template.Spec.Version
}

func (g *SchedulingGroup) SetImage(image string) {
	g.Spec.Template.Spec.Image = ptr.To(image)
}

func (g *SchedulingGroup) SetCluster(cluster string) {
	g.Spec.Cluster.Name = cluster
}

func (g *SchedulingGroup) Cluster() string {
	return g.Spec.Cluster.Name
}

func (*SchedulingGroup) Component() string {
	return v1alpha1.LabelValComponentScheduling
}

func (g *SchedulingGroup) Conditions() []metav1.Condition {
	return g.Status.Conditions
}

func (g *SchedulingGroup) SetConditions(conds []metav1.Condition) {
	g.Status.Conditions = conds
}

func (g *SchedulingGroup) ObservedGeneration() int64 {
	return g.Status.ObservedGeneration
}

func (g *SchedulingGroup) SetObservedGeneration(gen int64) {
	g.Status.ObservedGeneration = gen
}

func (g *SchedulingGroup) SetStatusVersion(version string) {
	g.Status.Version = version
}

func (g *SchedulingGroup) StatusVersion() string {
	return g.Status.Version
}

func (g *SchedulingGroup) SetStatusReplicas(replicas, ready, update, current int32) {
	g.Status.Replicas = replicas
	g.Status.ReadyReplicas = ready
	g.Status.UpdatedReplicas = update
	g.Status.CurrentReplicas = current
}

func (g *SchedulingGroup) StatusReplicas() (replicas, ready, update, current int32) {
	return g.Status.Replicas,
		g.Status.ReadyReplicas,
		g.Status.UpdatedReplicas,
		g.Status.CurrentReplicas
}

func (g *SchedulingGroup) SetStatusRevision(update, current string, collisionCount *int32) {
	g.Status.UpdateRevision = update
	g.Status.CurrentRevision = current
	g.Status.CollisionCount = collisionCount
}

func (g *SchedulingGroup) StatusRevision() (update, current string, collisionCount *int32) {
	return g.Status.UpdateRevision,
		g.Status.CurrentRevision,
		g.Status.CollisionCount
}

func (g *SchedulingGroup) SetStatusSelector(l string) {
	g.Status.Selector = l
}

func (g *SchedulingGroup) StatusSelector() string {
	return g.Status.Selector
}

func (g *SchedulingGroup) TemplateLabels() map[string]string {
	return g.Spec.Template.Labels
}

func (g *SchedulingGroup) TemplateAnnotations() map[string]string {
	return g.Spec.Template.Annotations
}

func (g *SchedulingGroup) Features() []metav1alpha1.Feature {
	return g.Spec.Features
}

func (g *SchedulingGroup) SetTemplateClusterTLS(ca, certKeyPair string) {
	if g.Spec.Template.Spec.Security == nil {
		g.Spec.Template.Spec.Security = &v1alpha1.Security{}
	}
	sec := g.Spec.Template.Spec.Security
	if sec.TLS == nil {
		sec.TLS = &v1alpha1.ComponentTLS{}
	}
	sec.TLS.Cluster = &v1alpha1.InternalTLS{}
	if ca != "" {
		sec.TLS.Cluster.CA = &v1alpha1.CAReference{
			Name: ca,
		}
	}
	if certKeyPair != "" {
		sec.TLS.Cluster.CertKeyPair = &v1alpha1.CertKeyPairReference{
			Name: certKeyPair,
		}
	}
}

func (g *SchedulingGroup) ClusterCertKeyPairSecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	return defaultName
}

func (g *SchedulingGroup) ClusterCASecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	return defaultName
}

func (g *SchedulingGroup) ClientCertKeyPairSecretName() string {
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Client != nil && sec.TLS.Client.CertKeyPair != nil {
		return sec.TLS.Client.CertKeyPair.Name
	}
	return g.Cluster() + "-cluster-client-secret"
}

func (g *SchedulingGroup) ClientCASecretName() string {
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Client != nil && sec.TLS.Client.CA != nil {
		return sec.TLS.Client.CA.Name
	}
	return g.Cluster() + "-cluster-client-secret"
}

func (g *SchedulingGroup) ClientInsecureSkipTLSVerify() bool {
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Client != nil && sec.TLS.Client.CA != nil {
		return sec.TLS.Client.InsecureSkipTLSVerify
	}
	return false
}

func (g *SchedulingGroup) MinReadySeconds() int64 {
	if g.Spec.MinReadySeconds == nil {
		return v1alpha1.DefaultSchedulingMinReadySeconds
	}
	return *g.Spec.MinReadySeconds
}
