//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package runtime

import (
	"time"
	"unsafe"

	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	metav1alpha1 "github.com/pingcap/tidb-operator/api/v2/meta/v1alpha1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/utils/ptr"
)

type (
	DMWorker v1alpha1.DMWorker
)

type DMWorkerTuple struct{}

var _ InstanceTuple[*v1alpha1.DMWorker, *DMWorker] = DMWorkerTuple{}

func (DMWorkerTuple) From(t *v1alpha1.DMWorker) *DMWorker {
	return FromDMWorker(t)
}

func (DMWorkerTuple) FromSlice(t []*v1alpha1.DMWorker) []*DMWorker {
	return FromDMWorkerSlice(t)
}

func (DMWorkerTuple) To(t *DMWorker) *v1alpha1.DMWorker {
	return ToDMWorker(t)
}

func (DMWorkerTuple) ToSlice(t []*DMWorker) []*v1alpha1.DMWorker {
	return ToDMWorkerSlice(t)
}

func FromDMWorker(in *v1alpha1.DMWorker) *DMWorker {
	return (*DMWorker)(in)
}

func ToDMWorker(in *DMWorker) *v1alpha1.DMWorker {
	return (*v1alpha1.DMWorker)(in)
}

func FromDMWorkerSlice(ins []*v1alpha1.DMWorker) []*DMWorker {
	return *(*[]*DMWorker)(unsafe.Pointer(&ins))
}

func ToDMWorkerSlice(ins []*DMWorker) []*v1alpha1.DMWorker {
	return *(*[]*v1alpha1.DMWorker)(unsafe.Pointer(&ins))
}

var _ Instance = &DMWorker{}

func (in *DMWorker) DeepCopyObject() runtime.Object {
	return (*v1alpha1.DMWorker)(in).DeepCopyObject()
}

func (in *DMWorker) To() *v1alpha1.DMWorker {
	return ToDMWorker(in)
}

func (in *DMWorker) GetTopology() v1alpha1.Topology {
	return in.Spec.Topology
}

func (in *DMWorker) SetTopology(t v1alpha1.Topology) {
	in.Spec.Topology = t
}

func (in *DMWorker) GetUpdateRevision() string {
	if in.Labels == nil {
		return ""
	}
	return in.Labels[v1alpha1.LabelKeyInstanceRevisionHash]
}

func (in *DMWorker) CurrentRevision() string {
	return in.Status.CurrentRevision
}

func (in *DMWorker) SetCurrentRevision(rev string) {
	in.Status.CurrentRevision = rev
}

func (in *DMWorker) IsReady() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}

	return cond.Status == metav1.ConditionTrue
}

func (in *DMWorker) IsNotRunning() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondRunning)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	return cond.Status == metav1.ConditionFalse
}

func (in *DMWorker) IsAvailable(minReadySeconds int64, now time.Time) bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	if cond.Status != metav1.ConditionTrue {
		return false
	}
	if minReadySeconds == 0 {
		return true
	}
	minReadySecondsDuration := time.Duration(minReadySeconds) * time.Second
	if !cond.LastTransitionTime.IsZero() && cond.LastTransitionTime.Add(minReadySecondsDuration).Before(now) {
		return true
	}

	return false
}

func (in *DMWorker) IsUpToDate() bool {
	return in.Status.ObservedGeneration == in.GetGeneration() && in.GetUpdateRevision() == in.Status.CurrentRevision
}

func (in *DMWorker) Conditions() []metav1.Condition {
	return in.Status.Conditions
}

func (in *DMWorker) SetConditions(conds []metav1.Condition) {
	in.Status.Conditions = conds
}

func (in *DMWorker) ObservedGeneration() int64 {
	return in.Status.ObservedGeneration
}

func (in *DMWorker) SetObservedGeneration(gen int64) {
	in.Status.ObservedGeneration = gen
}

func (in *DMWorker) SetCluster(cluster string) {
	in.Spec.Cluster.Name = cluster
}

func (in *DMWorker) Cluster() string {
	return in.Spec.Cluster.Name
}

func (*DMWorker) Component() string {
	return v1alpha1.LabelValComponentDMWorker
}

func (in *DMWorker) Volumes() []v1alpha1.Volume {
	return in.Spec.Volumes
}

func (in *DMWorker) PodOverlay() *v1alpha1.PodOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.Pod
}

func (in *DMWorker) PVCOverlay() []v1alpha1.NamedPersistentVolumeClaimOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.PersistentVolumeClaims
}

func (in *DMWorker) Features() []metav1alpha1.Feature {
	return in.Spec.Features
}

func (in *DMWorker) SetVersion(version string) {
	in.Spec.Version = version
}

func (in *DMWorker) Version() string {
	return in.Spec.Version
}

func (in *DMWorker) SetImage(image string) {
	in.Spec.Image = ptr.To(image)
}

func (in *DMWorker) Subdomain() string {
	return in.Spec.Subdomain
}

func (in *DMWorker) ServerLabels() map[string]string {
	return nil
}

func (in *DMWorker) ClusterCertKeyPairSecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *DMWorker) ClusterCASecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *DMWorker) IsOffline() bool {
	return false
}

func (in *DMWorker) IsStore() bool {
	return false
}

type (
	DMWorkerGroup v1alpha1.DMWorkerGroup
)

type DMWorkerGroupTuple struct{}

var _ GroupTuple[*v1alpha1.DMWorkerGroup, *DMWorkerGroup] = DMWorkerGroupTuple{}

func (DMWorkerGroupTuple) From(t *v1alpha1.DMWorkerGroup) *DMWorkerGroup {
	return FromDMWorkerGroup(t)
}

func (DMWorkerGroupTuple) FromSlice(t []*v1alpha1.DMWorkerGroup) []*DMWorkerGroup {
	return FromDMWorkerGroupSlice(t)
}

func (DMWorkerGroupTuple) To(t *DMWorkerGroup) *v1alpha1.DMWorkerGroup {
	return ToDMWorkerGroup(t)
}

func (DMWorkerGroupTuple) ToSlice(t []*DMWorkerGroup) []*v1alpha1.DMWorkerGroup {
	return ToDMWorkerGroupSlice(t)
}

func FromDMWorkerGroup(g *v1alpha1.DMWorkerGroup) *DMWorkerGroup {
	return (*DMWorkerGroup)(g)
}

func ToDMWorkerGroup(g *DMWorkerGroup) *v1alpha1.DMWorkerGroup {
	return (*v1alpha1.DMWorkerGroup)(g)
}

func FromDMWorkerGroupSlice(gs []*v1alpha1.DMWorkerGroup) []*DMWorkerGroup {
	return *(*[]*DMWorkerGroup)(unsafe.Pointer(&gs))
}

func ToDMWorkerGroupSlice(gs []*DMWorkerGroup) []*v1alpha1.DMWorkerGroup {
	return *(*[]*v1alpha1.DMWorkerGroup)(unsafe.Pointer(&gs))
}

var _ Group = &DMWorkerGroup{}

func (g *DMWorkerGroup) DeepCopyObject() runtime.Object {
	return (*v1alpha1.DMWorkerGroup)(g)
}

func (g *DMWorkerGroup) To() *v1alpha1.DMWorkerGroup {
	return ToDMWorkerGroup(g)
}

func (g *DMWorkerGroup) SetReplicas(replicas int32) {
	g.Spec.Replicas = &replicas
}

func (g *DMWorkerGroup) Replicas() int32 {
	if g.Spec.Replicas == nil {
		return 1
	}
	return *g.Spec.Replicas
}

func (g *DMWorkerGroup) SetVersion(version string) {
	g.Spec.Template.Spec.Version = version
}

func (g *DMWorkerGroup) Version() string {
	return g.Spec.Template.Spec.Version
}

func (g *DMWorkerGroup) SetImage(image string) {
	g.Spec.Template.Spec.Image = ptr.To(image)
}

func (g *DMWorkerGroup) SetCluster(cluster string) {
	g.Spec.Cluster.Name = cluster
}

func (g *DMWorkerGroup) Cluster() string {
	return g.Spec.Cluster.Name
}

func (*DMWorkerGroup) Component() string {
	return v1alpha1.LabelValComponentDMWorker
}

func (g *DMWorkerGroup) Conditions() []metav1.Condition {
	return g.Status.Conditions
}

func (g *DMWorkerGroup) SetConditions(conds []metav1.Condition) {
	g.Status.Conditions = conds
}

func (g *DMWorkerGroup) ObservedGeneration() int64 {
	return g.Status.ObservedGeneration
}

func (g *DMWorkerGroup) SetObservedGeneration(gen int64) {
	g.Status.ObservedGeneration = gen
}

func (g *DMWorkerGroup) SetStatusVersion(version string) {
	g.Status.Version = version
}

func (g *DMWorkerGroup) StatusVersion() string {
	return g.Status.Version
}

func (g *DMWorkerGroup) SetStatusReplicas(replicas, ready, update, current int32) {
	g.Status.Replicas = replicas
	g.Status.ReadyReplicas = ready
	g.Status.UpdatedReplicas = update
	g.Status.CurrentReplicas = current
}

func (g *DMWorkerGroup) StatusReplicas() (replicas, ready, update, current int32) {
	return g.Status.Replicas,
		g.Status.ReadyReplicas,
		g.Status.UpdatedReplicas,
		g.Status.CurrentReplicas
}

func (g *DMWorkerGroup) SetStatusRevision(update, current string, collisionCount *int32) {
	g.Status.UpdateRevision = update
	g.Status.CurrentRevision = current
	g.Status.CollisionCount = collisionCount
}

func (g *DMWorkerGroup) StatusRevision() (update, current string, collisionCount *int32) {
	return g.Status.UpdateRevision,
		g.Status.CurrentRevision,
		g.Status.CollisionCount
}

func (g *DMWorkerGroup) SetStatusSelector(l string) {
	g.Status.Selector = l
}

func (g *DMWorkerGroup) StatusSelector() string {
	return g.Status.Selector
}

func (g *DMWorkerGroup) TemplateLabels() map[string]string {
	return g.Spec.Template.Labels
}

func (g *DMWorkerGroup) TemplateAnnotations() map[string]string {
	return g.Spec.Template.Annotations
}

func (g *DMWorkerGroup) SetTemplateLabels(ls map[string]string) {
	g.Spec.Template.Labels = ls
}

func (g *DMWorkerGroup) SetTemplateAnnotations(anno map[string]string) {
	g.Spec.Template.Annotations = anno
}

func (g *DMWorkerGroup) Features() []metav1alpha1.Feature {
	return g.Spec.Features
}

func (g *DMWorkerGroup) SetTemplateClusterTLS(ca, certKeyPair string) {
	if g.Spec.Template.Spec.Security == nil {
		g.Spec.Template.Spec.Security = &v1alpha1.Security{}
	}
	sec := g.Spec.Template.Spec.Security
	if sec.TLS == nil {
		sec.TLS = &v1alpha1.ComponentTLSConfig{}
	}
	sec.TLS.Cluster = &v1alpha1.InternalTLS{}
	if ca != "" {
		sec.TLS.Cluster.CA = &v1alpha1.CAReference{
			Name: ca,
		}
	}
	if certKeyPair != "" {
		sec.TLS.Cluster.CertKeyPair = &v1alpha1.CertKeyPairReference{
			Name: certKeyPair,
		}
	}
}

func (g *DMWorkerGroup) ClusterCertKeyPairSecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	return defaultName
}

func (g *DMWorkerGroup) ClusterCASecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	return defaultName
}

func (g *DMWorkerGroup) MinReadySeconds() int64 {
	if g.Spec.MinReadySeconds == nil {
		return v1alpha1.DefaultDMWorkerMinReadySeconds
	}
	return *g.Spec.MinReadySeconds
}

func (g *DMWorkerGroup) SchedulePolicies() []v1alpha1.SchedulePolicy {
	return g.Spec.SchedulePolicies
}
