//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by runtime-gen. DO NOT EDIT.

package runtime

import (
	"time"
	"unsafe"

	"github.com/pingcap/tidb-operator/api/v2/core/v1alpha1"
	metav1alpha1 "github.com/pingcap/tidb-operator/api/v2/meta/v1alpha1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/utils/ptr"
)

type (
	ResourceManager v1alpha1.ResourceManager
)

type ResourceManagerTuple struct{}

var _ InstanceTuple[*v1alpha1.ResourceManager, *ResourceManager] = ResourceManagerTuple{}

func (ResourceManagerTuple) From(t *v1alpha1.ResourceManager) *ResourceManager {
	return FromResourceManager(t)
}

func (ResourceManagerTuple) FromSlice(t []*v1alpha1.ResourceManager) []*ResourceManager {
	return FromResourceManagerSlice(t)
}

func (ResourceManagerTuple) To(t *ResourceManager) *v1alpha1.ResourceManager {
	return ToResourceManager(t)
}

func (ResourceManagerTuple) ToSlice(t []*ResourceManager) []*v1alpha1.ResourceManager {
	return ToResourceManagerSlice(t)
}

func FromResourceManager(in *v1alpha1.ResourceManager) *ResourceManager {
	return (*ResourceManager)(in)
}

func ToResourceManager(in *ResourceManager) *v1alpha1.ResourceManager {
	return (*v1alpha1.ResourceManager)(in)
}

func FromResourceManagerSlice(ins []*v1alpha1.ResourceManager) []*ResourceManager {
	return *(*[]*ResourceManager)(unsafe.Pointer(&ins))
}

func ToResourceManagerSlice(ins []*ResourceManager) []*v1alpha1.ResourceManager {
	return *(*[]*v1alpha1.ResourceManager)(unsafe.Pointer(&ins))
}

var _ Instance = &ResourceManager{}

func (in *ResourceManager) DeepCopyObject() runtime.Object {
	return (*v1alpha1.ResourceManager)(in).DeepCopyObject()
}

func (in *ResourceManager) To() *v1alpha1.ResourceManager {
	return ToResourceManager(in)
}

func (in *ResourceManager) GetTopology() v1alpha1.Topology {
	return in.Spec.Topology
}

func (in *ResourceManager) SetTopology(t v1alpha1.Topology) {
	in.Spec.Topology = t
}

func (in *ResourceManager) GetUpdateRevision() string {
	if in.Labels == nil {
		return ""
	}
	return in.Labels[v1alpha1.LabelKeyInstanceRevisionHash]
}

func (in *ResourceManager) CurrentRevision() string {
	return in.Status.CurrentRevision
}

func (in *ResourceManager) SetCurrentRevision(rev string) {
	in.Status.CurrentRevision = rev
}

func (in *ResourceManager) IsReady() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}

	return cond.Status == metav1.ConditionTrue
}

func (in *ResourceManager) IsNotRunning() bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondRunning)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	return cond.Status == metav1.ConditionFalse
}

func (in *ResourceManager) IsAvailable(minReadySeconds int64, now time.Time) bool {
	cond := meta.FindStatusCondition(in.Status.Conditions, v1alpha1.CondReady)
	if cond == nil {
		return false
	}
	if cond.ObservedGeneration != in.GetGeneration() {
		return false
	}
	if cond.Status != metav1.ConditionTrue {
		return false
	}
	if minReadySeconds == 0 {
		return true
	}
	minReadySecondsDuration := time.Duration(minReadySeconds) * time.Second
	if !cond.LastTransitionTime.IsZero() && cond.LastTransitionTime.Add(minReadySecondsDuration).Before(now) {
		return true
	}

	return false
}

func (in *ResourceManager) IsUpToDate() bool {
	return in.Status.ObservedGeneration == in.GetGeneration() && in.GetUpdateRevision() == in.Status.CurrentRevision
}

func (in *ResourceManager) Conditions() []metav1.Condition {
	return in.Status.Conditions
}

func (in *ResourceManager) SetConditions(conds []metav1.Condition) {
	in.Status.Conditions = conds
}

func (in *ResourceManager) ObservedGeneration() int64 {
	return in.Status.ObservedGeneration
}

func (in *ResourceManager) SetObservedGeneration(gen int64) {
	in.Status.ObservedGeneration = gen
}

func (in *ResourceManager) SetCluster(cluster string) {
	in.Spec.Cluster.Name = cluster
}

func (in *ResourceManager) Cluster() string {
	return in.Spec.Cluster.Name
}

func (*ResourceManager) Component() string {
	return v1alpha1.LabelValComponentResourceManager
}

func (in *ResourceManager) Volumes() []v1alpha1.Volume {
	return in.Spec.Volumes
}

func (in *ResourceManager) PodOverlay() *v1alpha1.PodOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.Pod
}

func (in *ResourceManager) PVCOverlay() []v1alpha1.NamedPersistentVolumeClaimOverlay {
	if in.Spec.Overlay == nil {
		return nil
	}
	return in.Spec.Overlay.PersistentVolumeClaims
}

func (in *ResourceManager) Features() []metav1alpha1.Feature {
	return in.Spec.Features
}

func (in *ResourceManager) SetVersion(version string) {
	in.Spec.Version = version
}

func (in *ResourceManager) Version() string {
	return in.Spec.Version
}

func (in *ResourceManager) SetImage(image string) {
	in.Spec.Image = ptr.To(image)
}

func (in *ResourceManager) Subdomain() string {
	return in.Spec.Subdomain
}

func (in *ResourceManager) ClusterCertKeyPairSecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *ResourceManager) ClusterCASecretName() string {
	sec := in.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	prefix, _ := NamePrefixAndSuffix(in.GetName())
	return prefix + "-" + in.Component() + "-cluster-secret"
}

func (in *ResourceManager) IsOffline() bool {
	return false
}

func (in *ResourceManager) IsStore() bool {
	return false
}

type (
	ResourceManagerGroup v1alpha1.ResourceManagerGroup
)

type ResourceManagerGroupTuple struct{}

var _ GroupTuple[*v1alpha1.ResourceManagerGroup, *ResourceManagerGroup] = ResourceManagerGroupTuple{}

func (ResourceManagerGroupTuple) From(t *v1alpha1.ResourceManagerGroup) *ResourceManagerGroup {
	return FromResourceManagerGroup(t)
}

func (ResourceManagerGroupTuple) FromSlice(t []*v1alpha1.ResourceManagerGroup) []*ResourceManagerGroup {
	return FromResourceManagerGroupSlice(t)
}

func (ResourceManagerGroupTuple) To(t *ResourceManagerGroup) *v1alpha1.ResourceManagerGroup {
	return ToResourceManagerGroup(t)
}

func (ResourceManagerGroupTuple) ToSlice(t []*ResourceManagerGroup) []*v1alpha1.ResourceManagerGroup {
	return ToResourceManagerGroupSlice(t)
}

func FromResourceManagerGroup(g *v1alpha1.ResourceManagerGroup) *ResourceManagerGroup {
	return (*ResourceManagerGroup)(g)
}

func ToResourceManagerGroup(g *ResourceManagerGroup) *v1alpha1.ResourceManagerGroup {
	return (*v1alpha1.ResourceManagerGroup)(g)
}

func FromResourceManagerGroupSlice(gs []*v1alpha1.ResourceManagerGroup) []*ResourceManagerGroup {
	return *(*[]*ResourceManagerGroup)(unsafe.Pointer(&gs))
}

func ToResourceManagerGroupSlice(gs []*ResourceManagerGroup) []*v1alpha1.ResourceManagerGroup {
	return *(*[]*v1alpha1.ResourceManagerGroup)(unsafe.Pointer(&gs))
}

var _ Group = &ResourceManagerGroup{}

func (g *ResourceManagerGroup) DeepCopyObject() runtime.Object {
	return (*v1alpha1.ResourceManagerGroup)(g)
}

func (g *ResourceManagerGroup) To() *v1alpha1.ResourceManagerGroup {
	return ToResourceManagerGroup(g)
}

func (g *ResourceManagerGroup) SetReplicas(replicas int32) {
	g.Spec.Replicas = &replicas
}

func (g *ResourceManagerGroup) Replicas() int32 {
	if g.Spec.Replicas == nil {
		return 1
	}
	return *g.Spec.Replicas
}

func (g *ResourceManagerGroup) SetVersion(version string) {
	g.Spec.Template.Spec.Version = version
}

func (g *ResourceManagerGroup) Version() string {
	return g.Spec.Template.Spec.Version
}

func (g *ResourceManagerGroup) SetImage(image string) {
	g.Spec.Template.Spec.Image = ptr.To(image)
}

func (g *ResourceManagerGroup) SetCluster(cluster string) {
	g.Spec.Cluster.Name = cluster
}

func (g *ResourceManagerGroup) Cluster() string {
	return g.Spec.Cluster.Name
}

func (*ResourceManagerGroup) Component() string {
	return v1alpha1.LabelValComponentResourceManager
}

func (g *ResourceManagerGroup) Conditions() []metav1.Condition {
	return g.Status.Conditions
}

func (g *ResourceManagerGroup) SetConditions(conds []metav1.Condition) {
	g.Status.Conditions = conds
}

func (g *ResourceManagerGroup) ObservedGeneration() int64 {
	return g.Status.ObservedGeneration
}

func (g *ResourceManagerGroup) SetObservedGeneration(gen int64) {
	g.Status.ObservedGeneration = gen
}

func (g *ResourceManagerGroup) SetStatusVersion(version string) {
	g.Status.Version = version
}

func (g *ResourceManagerGroup) StatusVersion() string {
	return g.Status.Version
}

func (g *ResourceManagerGroup) SetStatusReplicas(replicas, ready, update, current int32) {
	g.Status.Replicas = replicas
	g.Status.ReadyReplicas = ready
	g.Status.UpdatedReplicas = update
	g.Status.CurrentReplicas = current
}

func (g *ResourceManagerGroup) StatusReplicas() (replicas, ready, update, current int32) {
	return g.Status.Replicas,
		g.Status.ReadyReplicas,
		g.Status.UpdatedReplicas,
		g.Status.CurrentReplicas
}

func (g *ResourceManagerGroup) SetStatusRevision(update, current string, collisionCount *int32) {
	g.Status.UpdateRevision = update
	g.Status.CurrentRevision = current
	g.Status.CollisionCount = collisionCount
}

func (g *ResourceManagerGroup) StatusRevision() (update, current string, collisionCount *int32) {
	return g.Status.UpdateRevision,
		g.Status.CurrentRevision,
		g.Status.CollisionCount
}

func (g *ResourceManagerGroup) SetStatusSelector(l string) {
	g.Status.Selector = l
}

func (g *ResourceManagerGroup) StatusSelector() string {
	return g.Status.Selector
}

func (g *ResourceManagerGroup) TemplateLabels() map[string]string {
	return g.Spec.Template.Labels
}

func (g *ResourceManagerGroup) TemplateAnnotations() map[string]string {
	return g.Spec.Template.Annotations
}

func (g *ResourceManagerGroup) SetTemplateLabels(ls map[string]string) {
	g.Spec.Template.Labels = ls
}

func (g *ResourceManagerGroup) SetTemplateAnnotations(anno map[string]string) {
	g.Spec.Template.Annotations = anno
}

func (g *ResourceManagerGroup) Features() []metav1alpha1.Feature {
	return g.Spec.Features
}

func (g *ResourceManagerGroup) SetTemplateClusterTLS(ca, certKeyPair string) {
	if g.Spec.Template.Spec.Security == nil {
		g.Spec.Template.Spec.Security = &v1alpha1.Security{}
	}
	sec := g.Spec.Template.Spec.Security
	if sec.TLS == nil {
		sec.TLS = &v1alpha1.ComponentTLSConfig{}
	}
	sec.TLS.Cluster = &v1alpha1.InternalTLS{}
	if ca != "" {
		sec.TLS.Cluster.CA = &v1alpha1.CAReference{
			Name: ca,
		}
	}
	if certKeyPair != "" {
		sec.TLS.Cluster.CertKeyPair = &v1alpha1.CertKeyPairReference{
			Name: certKeyPair,
		}
	}
}

func (g *ResourceManagerGroup) ClusterCertKeyPairSecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CertKeyPair != nil {
		return sec.TLS.Cluster.CertKeyPair.Name
	}
	return defaultName
}

func (g *ResourceManagerGroup) ClusterCASecretName() string {
	defaultName := g.Name + "-" + g.Component() + "-cluster-secret"
	sec := g.Spec.Template.Spec.Security
	if sec != nil && sec.TLS != nil && sec.TLS.Cluster != nil && sec.TLS.Cluster.CA != nil {
		return sec.TLS.Cluster.CA.Name
	}
	return defaultName
}

func (g *ResourceManagerGroup) MinReadySeconds() int64 {
	if g.Spec.MinReadySeconds == nil {
		return v1alpha1.DefaultResourceManagerMinReadySeconds
	}
	return *g.Spec.MinReadySeconds
}

func (g *ResourceManagerGroup) SchedulePolicies() []v1alpha1.SchedulePolicy {
	return g.Spec.SchedulePolicies
}
