// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTiDBNGMonitorings implements TiDBNGMonitoringInterface
type FakeTiDBNGMonitorings struct {
	Fake *FakePingcapV1alpha1
	ns   string
}

var tidbngmonitoringsResource = schema.GroupVersionResource{Group: "pingcap.com", Version: "v1alpha1", Resource: "tidbngmonitorings"}

var tidbngmonitoringsKind = schema.GroupVersionKind{Group: "pingcap.com", Version: "v1alpha1", Kind: "TiDBNGMonitoring"}

// Get takes name of the tiDBNGMonitoring, and returns the corresponding tiDBNGMonitoring object, and an error if there is any.
func (c *FakeTiDBNGMonitorings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TiDBNGMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tidbngmonitoringsResource, c.ns, name), &v1alpha1.TiDBNGMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TiDBNGMonitoring), err
}

// List takes label and field selectors, and returns the list of TiDBNGMonitorings that match those selectors.
func (c *FakeTiDBNGMonitorings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TiDBNGMonitoringList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tidbngmonitoringsResource, tidbngmonitoringsKind, c.ns, opts), &v1alpha1.TiDBNGMonitoringList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TiDBNGMonitoringList{ListMeta: obj.(*v1alpha1.TiDBNGMonitoringList).ListMeta}
	for _, item := range obj.(*v1alpha1.TiDBNGMonitoringList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tiDBNGMonitorings.
func (c *FakeTiDBNGMonitorings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tidbngmonitoringsResource, c.ns, opts))

}

// Create takes the representation of a tiDBNGMonitoring and creates it.  Returns the server's representation of the tiDBNGMonitoring, and an error, if there is any.
func (c *FakeTiDBNGMonitorings) Create(ctx context.Context, tiDBNGMonitoring *v1alpha1.TiDBNGMonitoring, opts v1.CreateOptions) (result *v1alpha1.TiDBNGMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tidbngmonitoringsResource, c.ns, tiDBNGMonitoring), &v1alpha1.TiDBNGMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TiDBNGMonitoring), err
}

// Update takes the representation of a tiDBNGMonitoring and updates it. Returns the server's representation of the tiDBNGMonitoring, and an error, if there is any.
func (c *FakeTiDBNGMonitorings) Update(ctx context.Context, tiDBNGMonitoring *v1alpha1.TiDBNGMonitoring, opts v1.UpdateOptions) (result *v1alpha1.TiDBNGMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tidbngmonitoringsResource, c.ns, tiDBNGMonitoring), &v1alpha1.TiDBNGMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TiDBNGMonitoring), err
}

// Delete takes name of the tiDBNGMonitoring and deletes it. Returns an error if one occurs.
func (c *FakeTiDBNGMonitorings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tidbngmonitoringsResource, c.ns, name), &v1alpha1.TiDBNGMonitoring{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTiDBNGMonitorings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tidbngmonitoringsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TiDBNGMonitoringList{})
	return err
}

// Patch applies the patch and returns the patched tiDBNGMonitoring.
func (c *FakeTiDBNGMonitorings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TiDBNGMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tidbngmonitoringsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TiDBNGMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TiDBNGMonitoring), err
}
