//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by feature-gen. DO NOT EDIT.

package features

import (
	meta "github.com/pingcap/tidb-operator/api/v2/meta/v1alpha1"
)

const CurrentFeatureGateDefinitionHash = "sha256:7f739c68838babaf882fb52819d0093f1478e11ce49da6b3a6592c078b92944d"

var logs = [][]FeatureLog{
	{
		{Name: meta.ClusterSubdomain, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.DisablePDDefaultReadinessProbe, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.FeatureModification, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.IndependentKVEngineWorker, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.MultiPDGroup, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.SessionTokenSigning, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.TerminableLogTailer, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.TiCDCDynamicSecretSyncer, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.UsePDReadyAPI, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.UsePDReadyAPIV2, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.UseSchedulingReadyAPI, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.UseTSOReadyAPI, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.UseTiFlashReadyAPI, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.UseTiKVReadyAPI, Stage: meta.FeatureStageAlpha, Default: false},
		{Name: meta.VolumeAttributesClass, Stage: meta.FeatureStageAlpha, Default: false},
	},
}

var hashToRev = map[string]int{
	"sha256:7f739c68838babaf882fb52819d0093f1478e11ce49da6b3a6592c078b92944d": 0,
}
