// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1"
	scheme "github.com/pingcap/tidb-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CompactBackupsGetter has a method to return a CompactBackupInterface.
// A group's client should implement this interface.
type CompactBackupsGetter interface {
	CompactBackups(namespace string) CompactBackupInterface
}

// CompactBackupInterface has methods to work with CompactBackup resources.
type CompactBackupInterface interface {
	Create(ctx context.Context, compactBackup *v1alpha1.CompactBackup, opts v1.CreateOptions) (*v1alpha1.CompactBackup, error)
	Update(ctx context.Context, compactBackup *v1alpha1.CompactBackup, opts v1.UpdateOptions) (*v1alpha1.CompactBackup, error)
	UpdateStatus(ctx context.Context, compactBackup *v1alpha1.CompactBackup, opts v1.UpdateOptions) (*v1alpha1.CompactBackup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CompactBackup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CompactBackupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CompactBackup, err error)
	CompactBackupExpansion
}

// compactBackups implements CompactBackupInterface
type compactBackups struct {
	client rest.Interface
	ns     string
}

// newCompactBackups returns a CompactBackups
func newCompactBackups(c *PingcapV1alpha1Client, namespace string) *compactBackups {
	return &compactBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the compactBackup, and returns the corresponding compactBackup object, and an error if there is any.
func (c *compactBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CompactBackup, err error) {
	result = &v1alpha1.CompactBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("compactbackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CompactBackups that match those selectors.
func (c *compactBackups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CompactBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CompactBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("compactbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested compactBackups.
func (c *compactBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("compactbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a compactBackup and creates it.  Returns the server's representation of the compactBackup, and an error, if there is any.
func (c *compactBackups) Create(ctx context.Context, compactBackup *v1alpha1.CompactBackup, opts v1.CreateOptions) (result *v1alpha1.CompactBackup, err error) {
	result = &v1alpha1.CompactBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("compactbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(compactBackup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a compactBackup and updates it. Returns the server's representation of the compactBackup, and an error, if there is any.
func (c *compactBackups) Update(ctx context.Context, compactBackup *v1alpha1.CompactBackup, opts v1.UpdateOptions) (result *v1alpha1.CompactBackup, err error) {
	result = &v1alpha1.CompactBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("compactbackups").
		Name(compactBackup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(compactBackup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *compactBackups) UpdateStatus(ctx context.Context, compactBackup *v1alpha1.CompactBackup, opts v1.UpdateOptions) (result *v1alpha1.CompactBackup, err error) {
	result = &v1alpha1.CompactBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("compactbackups").
		Name(compactBackup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(compactBackup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the compactBackup and deletes it. Returns an error if one occurs.
func (c *compactBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("compactbackups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *compactBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("compactbackups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched compactBackup.
func (c *compactBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CompactBackup, err error) {
	result = &v1alpha1.CompactBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("compactbackups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
