// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1"
	scheme "github.com/pingcap/tidb-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TiDBGroupsGetter has a method to return a TiDBGroupInterface.
// A group's client should implement this interface.
type TiDBGroupsGetter interface {
	TiDBGroups(namespace string) TiDBGroupInterface
}

// TiDBGroupInterface has methods to work with TiDBGroup resources.
type TiDBGroupInterface interface {
	Create(*v1alpha1.TiDBGroup) (*v1alpha1.TiDBGroup, error)
	Update(*v1alpha1.TiDBGroup) (*v1alpha1.TiDBGroup, error)
	UpdateStatus(*v1alpha1.TiDBGroup) (*v1alpha1.TiDBGroup, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TiDBGroup, error)
	List(opts v1.ListOptions) (*v1alpha1.TiDBGroupList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TiDBGroup, err error)
	TiDBGroupExpansion
}

// tiDBGroups implements TiDBGroupInterface
type tiDBGroups struct {
	client rest.Interface
	ns     string
}

// newTiDBGroups returns a TiDBGroups
func newTiDBGroups(c *PingcapV1alpha1Client, namespace string) *tiDBGroups {
	return &tiDBGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tiDBGroup, and returns the corresponding tiDBGroup object, and an error if there is any.
func (c *tiDBGroups) Get(name string, options v1.GetOptions) (result *v1alpha1.TiDBGroup, err error) {
	result = &v1alpha1.TiDBGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tidbgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TiDBGroups that match those selectors.
func (c *tiDBGroups) List(opts v1.ListOptions) (result *v1alpha1.TiDBGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TiDBGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tidbgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tiDBGroups.
func (c *tiDBGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tidbgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a tiDBGroup and creates it.  Returns the server's representation of the tiDBGroup, and an error, if there is any.
func (c *tiDBGroups) Create(tiDBGroup *v1alpha1.TiDBGroup) (result *v1alpha1.TiDBGroup, err error) {
	result = &v1alpha1.TiDBGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tidbgroups").
		Body(tiDBGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tiDBGroup and updates it. Returns the server's representation of the tiDBGroup, and an error, if there is any.
func (c *tiDBGroups) Update(tiDBGroup *v1alpha1.TiDBGroup) (result *v1alpha1.TiDBGroup, err error) {
	result = &v1alpha1.TiDBGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tidbgroups").
		Name(tiDBGroup.Name).
		Body(tiDBGroup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *tiDBGroups) UpdateStatus(tiDBGroup *v1alpha1.TiDBGroup) (result *v1alpha1.TiDBGroup, err error) {
	result = &v1alpha1.TiDBGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tidbgroups").
		Name(tiDBGroup.Name).
		SubResource("status").
		Body(tiDBGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the tiDBGroup and deletes it. Returns an error if one occurs.
func (c *tiDBGroups) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tidbgroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tiDBGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tidbgroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tiDBGroup.
func (c *tiDBGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TiDBGroup, err error) {
	result = &v1alpha1.TiDBGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tidbgroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
